[last_checklist]
filename = "piscine-c/semaine01_c00-c02.md"
selected_at = "2025-10-16T16:43:51"

[ui]
theme = "auto"
progress_style = "bar"
compact_mode = false
show_focus = true

[stats]
total_checks = 0
micro_victories_today = 0
last_victory = "2025-06-20T17:38:00"

[profile]
adhd_mode = false

[paths]
checklist_dir = "checklists"
log_dir = "logs"

[custom]
